services:
  api:
    build: .
    image: ghcr.io/alfremu/academia2025-challenge:latest
    env_file: .env
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - app-net
    volumes:
      - ./logs:/app/logs

  postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432" # opcional, sólo si querés conectarte desde tu host (DBeaver, psql)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

networks:
  app-net:

volumes:
  pgdata:
