services:
  api:
    image: ghcr.io/alfremu/academia2025-challenge:latest
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${POSTGRES_NAME}
      DB_USER: ${POSTGRES_USER}
    command:
      - /bin/sh
      - -lc
      - 'export DB_PASSWORD=$$(cat /run/secrets/db_password) && exec node dist/app.js'
    secrets:
      - db_password
    networks:
      - app-net
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
        delay: 5s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 30s
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.10"
          memory: 128M
      placement:
        max_replicas_per_node: 3
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/api-docs.json >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 30s
      resources:
        limits:
          cpus: "0.40"
          memory: 512M
        reservations:
          cpus: "0.10"
          memory: 128M

  nginx:
    image: nginx:1.25.5-alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
    networks:
      - app-net
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          memory: 128M

networks:
  app-net:
    driver: overlay
    attachable: true

volumes:
  pgdata:

secrets:
  db_password:
    external: true

configs:
  nginx_config:
    file: ./nginx.conf
