name: Build & Push (GHCR)

on:
  push:
    branches: [ main ]         # build en cada push a main
    tags:     [ 'v*.*.*' ]     # y en releases tipo v0.1.0

permissions:
  contents: read
  packages: write              

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: alfremu/academia2025-challenge   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=sha-${{ github.sha }}          # único por commit
            type=ref,event=tag                            # usa el tag (v0.1.0)
            type=raw,value=latest,enable={{is_default_branch}}  # latest en main

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max
