name: deploy.yml

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create remote directory
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: mkdir -p ~/academia2025-challenge

      - name: Copy docker-compose.prod.yml to VM
        run: |
          echo "${{ secrets.SSH_KEY }}" > /tmp/private_key
          chmod 600 /tmp/private_key

          scp -i /tmp/private_key -P ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no \
            docker-compose.prod.yml \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/academia2025-challenge/

      - name: Copy Nginx folder to VM
        run: |
          scp -r -i /tmp/private_key -P ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no \
            Nginx \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/academia2025-challenge/

          rm /tmp/private_key

      - name: Deploy with Docker Swarm
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/academia2025-challenge

            echo "Haciendo login a GHCR..."
            echo ${{ secrets.REGISTRY_TOKEN }} | docker login ghcr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

            echo "Inicializando Swarm (si hace falta)"
            docker swarm init --advertise-addr $(hostname -I | awk '{print $1}') || true

            echo "Eliminando stack existente (si existe)"
            docker stack rm academiachallenge || true
            sleep 6

            echo "Desplegando nuevo stack"
            docker stack deploy -c docker-compose.prod.yml academiachallenge

