name: Deploy to Docker Swarm

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create remote directory
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: mkdir -p ~/academia2025-challenge

      - name: Copy files to VM
        run: |
          echo "${{ secrets.SSH_KEY }}" > /tmp/private_key
          chmod 600 /tmp/private_key

          scp -i /tmp/private_key -P ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no \
            docker-compose.prod.yml \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/academia2025-challenge/

          scp -i /tmp/private_key -P ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no -r \
            Nginx \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/academia2025-challenge/

          rm /tmp/private_key          

      - name: Deploy with Docker Swarm
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/academia2025-challenge

            echo "Inicializando Swarm"
            docker swarm init --advertise-addr $(hostname -I | awk '{print $1}') || true

            echo "Eliminando stack existente"
            docker stack rm academiachallenge || true
            echo "Esperando a que se liberen recursos..."
            sleep 6

            echo "Eliminando red si existe"
            docker network rm academiachallenge_app-net || true
            echo "Esperando..."
            sleep 3

            echo "Esperando a que la red se libere..."
            while docker network inspect academiachallenge_app-net >/dev/null 2>&1; do
            echo "La red todavía existe, esperando..."
            sleep 2
            done

            echo "Creando red overlay app-net"
            docker network create --driver overlay --attachable academiachallenge_app-net

            echo "Desplegando nuevo stack"
            docker stack deploy -c docker-compose.prod.yml academiachallenge
