name: Deploy to VM (via ngrok + SCP)

on:
  workflow_dispatch: {}
  push:
    tags: ['v*.*.*']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > id_vm
          chmod 600 id_vm

      - name: Copy docker-compose to VM
        run: |
          scp -P $SSH_PORT -i id_vm -o StrictHostKeyChecking=no \
            docker-compose.prod.yml \
            $SSH_USER@$SSH_HOST:~/academia2025-challenge/

      - name: Deploy on VM
        run: |
          ssh -p $SSH_PORT -i id_vm -o StrictHostKeyChecking=no \
            $SSH_USER@$SSH_HOST \
            "cd ~/academia2025-challenge && docker compose -f docker-compose.prod.yml up -d --build"

      - name: Clean up SSH key
        run: rm id_vm
