name: deploy.yml

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create remote directory
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: mkdir -p ~/academia2025-challenge

      - name: Copy files to VM
        run: |
          echo "${{ secrets.SSH_KEY }}" > /tmp/private_key
          chmod 600 /tmp/private_key

          scp -i /tmp/private_key -P ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no \
            docker-compose.prod.yml \
            -r Nginx \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/academia2025-challenge/

          rm /tmp/private_key

      - name: Deploy with Docker Swarm
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/academia2025-challenge

            echo "Iniciando Swarm si no está activo"
            docker swarm init --advertise-addr $(hostname -I | awk '{print $1}') || true

            echo "Eliminando stack anterior si existe"
            docker stack rm academiachallenge || true
            sleep 6

            echo "Creando red overlay si no existe"
            docker network rm app_network || true
            docker network create --driver overlay --attachable app_network

            echo "Haciendo deploy del stack"
            docker stack deploy -c docker-compose.prod.yml academiachallenge

            docker network create --driver overlay --attachable app-net

            echo "Haciendo deploy del stack"
            docker stack deploy -c docker-compose.prod.yml academiachallenge
